[pytest]
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    smoke: Smoke Tests
    regression: Regression Tests
    integration: Integration Tests
    validation: Valid Scenarios
    sanity: Smoke Tests
# Method A: Set a default browser flag using addopts
#addopts = --browser chromium
#addopts = "--browser chromium --browser firefox --browser webkit --git browser-channel msedge"


# Method B: Define custom variables for your test suite to parse
[drivers]
supported_browsers = chrome firefox edge